"use strict";
exports.__esModule = true;
exports["default"] = [
    'Anal Salute',
    'backfire',
    'bake breeze biscuits',
    'bake brownies',
    'bark',
    'bend a valve',
    'Beep your horn',
    'Blast the chair',
    'blow dirt',
    'blow dust',
    'blow a fart',
    'blow a gasket',
    'blow kisses',
    'blow mud',
    'blow smoke',
    'Blow the big brown horn',
    'blow the sparkplugs',
    'blurt',
    'boff',
    'Bottom blast',
    'Bottom burp',
    'boom-boom',
    'break the seam',
    'break wind',
    'buang angin',
    'bust ass',
    'Buttock bassoon',
    'Butt burp',
    'Butt tuba',
    'butt yodeling',
    'chemold',
    "clear one's throat",
    'cleft a boofer',
    "colon bowlin'",
    'cook eggs',
    'couper le fromage',
    'crack ass',
    'crepitate',
    'crop dusting',
    'cut a gasser',
    'cut a melon',
    'cut chedder',
    'cut muffins',
    'cut one',
    'cut the cheese',
    'cut the provolone',
    'Cut a stinker',
    'Cut the wind',
    'deal one',
    'degas',
    "dot'dot",
    'draw mud from the bottom of the pond',
    'drop ass',
    'Drop a bomb',
    'drop a cookie',
    'drop a fart',
    'drop a ringo',
    'drop a rose',
    'drop one',
    "drop one's guts",
    'effluviate',
    'emit a fart',
    'erupt one',
    'fardullah',
    'fart',
    'fart like a popcorn machine',
    'fessa',
    'flatulate',
    'Flatulence',
    'float an air biscuit',
    'frump',
    'Funky rollers',
    'furzen',
    'fuss',
    'Gaseous intestinal by-products',
    'get expelled from stool',
    'grunt',
    'guff',
    'heiny burp',
    'he o koita',
    'here comes Freddie',
    'Honk',
    'HUMrrhoids',
    'Jag fis',
    'kentut',
    'kill the canary',
    'launch a wifter',
    'lay a fart',
    'lay a jellybean',
    'Let a Beefer',
    'Let each little bean be heard',
    'let a windy',
    'let fly a fart',
    'let Freddie out of jail',
    'let one',
    'make a stink',
    'make cheese',
    'make methane',
    'make some underleg noise',
    'Mating call of the barking spider',
    'Mexican jet propulsion',
    "ot'ot",
    'pass gas',
    'Pass wind',
    'peidar',
    'peter',
    'piffle',
    'pollute the atmosphere',
    'poopski',
    'poot',
    'pop corn',
    'pop off',
    'pritz',
    'puf',
    'Puff, the Magic Dragon!',
    'pukat',
    'queimar a bota',
    'Rebuild the ozone layer one poof at a time',
    'Rectal honk',
    'Rectal shout',
    'refine shit particles',
    'release intestinal gases',
    'Release a tree monkey from captivity',
    'ringo',
    'rip one',
    'rip the canvas',
    'Ripple Fart',
    'roar from the rear',
    'shit the bed',
    'shoot bunnies',
    'Shoot the cannon',
    'sink my battleship',
    "sneeze in one's pants",
    "spider's barking",
    "spill one's guts",
    'split the seam',
    'start a Harley',
    'start the engine',
    'step on a duck',
    'step on a frog',
    'step on a fart snake',
    'stink out loud',
    'stomp on the barking spider',
    'strike mud',
    'strip a gear',
    'supply it',
    'taint ripper',
    'toot',
    'Toot your own horn',
    'To speak German',
    'Trouser cough',
    'Trouser trumpet',
    'vent',
    'winden laten',
];
